{
 "title": "Solar",
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  {
   "title": "Current power surplus/deficit",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  epoch_timestamp AS \"time\",\n  generation + consumption as \"available power\"\nFROM current_power\nWHERE\n  $__unixEpochFilter(epoch_timestamp)\nORDER BY epoch_timestamp"
    }
   ]
  },
  {
   "title": "Power Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "solar",
     "rawSql": "SELECT SUM(cost) FROM solar.power_cost where $__unixEpochFilter(period_end_epoch)"
    }
   ]
  },
  {
   "title": "Total Generation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(generation)/3600\nFROM current_power\nWHERE $__unixEpochFilter(epoch_timestamp)"
    }
   ]
  },
  {
   "title": "Total Consumption",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT -sum(consumption)/3600\nFROM current_power\nWHERE $__unixEpochFilter(epoch_timestamp)"
    }
   ]
  },
  {
   "title": "Total Exported",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (sum(generation)+sum(consumption))/3600\r\nFROM current_power\r\nWHERE $__unixEpochFilter(epoch_timestamp)\r\nAND (generation + consumption) > 0"
    }
   ]
  },
  {
   "title": "Total Imported",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT -(sum(generation)+sum(consumption))/3600\r\nFROM current_power\r\nWHERE $__unixEpochFilter(epoch_timestamp)\r\nAND (generation + consumption) < 0"
    }
   ]
  },
  {
   "title": "Power Generation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  epoch_timestamp AS \"time\",\n  generation\nFROM current_power\nWHERE\n  $__unixEpochFilter(epoch_timestamp)\nORDER BY epoch_timestamp"
    }
   ]
  },
  {
   "title": "Power Generation - East/West Split",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  period_end_epoch AS \"time\",\n  string1_power AS \"West Panels Power Output\",\n  string2_power AS \"East Panels Power Output\"\nFROM string_power\nORDER BY period_end_epoch"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  epoch_timestamp AS \"time\",\n  -consumption\nFROM current_power\nWHERE\n  $__unixEpochFilter(epoch_timestamp)\nORDER BY epoch_timestamp"
    }
   ]
  },
  {
   "title": "Today's Solar Forecast",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  period_end_epoch AS \"time\",\n  pv_estimate AS \"Best Estimate\",\n  pv_estimate10 AS \"Low Estimate\",\n  pv_estimate90 AS \"High Estimate\"\nFROM generation_forecast\nWHERE\n  $__unixEpochFilter(period_end_epoch)\nORDER BY period_end_epoch"
    }
   ]
  },
  {
   "title": "Weekly Solar Forecast",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  period_end_epoch AS \"time\",\n  pv_estimate AS \"Best Estimate\",\n  pv_estimate10 AS \"Low Estimate\",\n  pv_estimate90 AS \"High Estimate\"\nFROM generation_forecast\nWHERE\n  $__unixEpochFilter(period_end_epoch)\nORDER BY period_end_epoch"
    }
   ]
  }
 ]
}